import json
import os
from typing import Any, Optional

from providers.registry import generate_text, list_providers, resolve_llm

MOCK_MODE = os.environ.get("LLM_MOCK", "").lower() in ("1", "true", "yes")


def _llm_kwargs(
    provider: Optional[str] = None,
    model: Optional[str] = None,
    api_key: Optional[str] = None,
) -> dict[str, Optional[str]]:
    return {"provider": provider, "model": model, "api_key": api_key}


def _use_mock(provider: Optional[str] = None, api_key: Optional[str] = None) -> bool:
    if MOCK_MODE:
        return True
    try:
        prov, _, key = resolve_llm(provider, api_key=api_key)
        return not prov.is_available(key)
    except Exception:
        return True


def _generate(
    prompt: str,
    system: str = "",
    provider: Optional[str] = None,
    model: Optional[str] = None,
    api_key: Optional[str] = None,
) -> tuple[str, str, str]:
    """Returns (text, provider_id, model_id)."""
    if _use_mock(provider, api_key):
        return "", "mock", "mock"
    try:
        resp = generate_text(prompt, system=system, provider=provider, model=model, api_key=api_key)
        return resp.text, resp.provider, resp.model
    except Exception as exc:
        raise RuntimeError(str(exc)) from exc


def _mock_codegen(prompt: str) -> str:
    return f'''# Generated for: {prompt[:80]}
import pandas as pd
result = df1.describe() if "df1" in dir() else pd.DataFrame({{"note": ["upload a dataset first"]}})
print(result)
'''


def _mock_final_answer(prompt: str, stdout: str) -> str:
    return f"## Quick Analysis\n\n**Question:** {prompt}\n\n**Findings:**\n\n```\n{stdout[:2000]}\n```\n"


def _strip_code_fence(text: str) -> str:
    code = text.strip()
    if code.startswith("```"):
        code = code.split("```", 2)[1]
        if code.startswith("python"):
            code = code[6:]
        code = code.strip()
    return code


def direct_answer(
    prompt: str,
    context: str = "",
    provider: Optional[str] = None,
    model: Optional[str] = None,
    api_key: Optional[str] = None,
) -> dict[str, Any]:
    if _use_mock(provider, api_key):
        return {
            "final_answer": f"I can help with that. {prompt}",
            "mode": "direct",
            "provider": "mock",
            "model": "mock",
            "chart_objects": [],
        }
    system = (
        "You are AVIAGENT, a helpful agentic analytics assistant. "
        "Answer directly and naturally. If the user asks for data analysis but has not "
        "attached a dataset, ask them to attach a CSV, Excel, or Parquet file. "
        "Do not invent dataset-specific numbers."
    )
    full_prompt = prompt
    if context.strip():
        full_prompt = f"Additional instruction:\n{context.strip()}\n\nUser message:\n{prompt}"
    text, prov_id, model_id = _generate(full_prompt, system=system, provider=provider, model=model, api_key=api_key)
    return {
        "final_answer": text,
        "mode": "direct",
        "provider": prov_id,
        "model": model_id,
        "chart_objects": [],
    }


def generate_code(
    prompt: str,
    context: str = "",
    critic_feedback: str = "",
    provider: Optional[str] = None,
    model: Optional[str] = None,
    api_key: Optional[str] = None,
) -> dict[str, Any]:
    full_prompt = prompt
    if context:
        full_prompt = f"{context}\n\nUser request:\n{prompt}"
    if critic_feedback:
        full_prompt += f"\n\nFix based on critic feedback:\n{critic_feedback}"
    if _use_mock(provider, api_key):
        code = _mock_codegen(prompt)
        return {
            "code": code,
            "explanation": "Mock codegen — configure Ollama, Hugging Face, or add a paid API key",
            "provider": "mock",
            "model": "mock",
        }
    system = (
        "You are a Python data analyst. Return only executable pandas/numpy code. "
        "DataFrames are df1, df2, ... Print labeled results."
    )
    text, prov_id, model_id = _generate(full_prompt, system=system, provider=provider, model=model, api_key=api_key)
    code = _strip_code_fence(text)
    return {"code": code, "explanation": f"Generated by {prov_id}/{model_id}", "provider": prov_id, "model": model_id}


def critic_evaluate(
    code: str,
    run_result: dict,
    prompt: str,
    provider: Optional[str] = None,
    model: Optional[str] = None,
    api_key: Optional[str] = None,
) -> dict[str, Any]:
    if _use_mock(provider, api_key):
        if run_result.get("status") == "completed":
            return {"approved": True, "feedback": "Mock critic approved"}
        return {"approved": False, "feedback": run_result.get("error", {}).get("message", "Execution failed")}
    critic_prompt = (
        f"Approve Python analysis code if output answers the question.\n"
        f"Question: {prompt}\nCode:\n{code}\nOutput logs:\n{run_result.get('logs','')}\n"
        f"Reply JSON: {{\"approved\": true/false, \"feedback\": \"...\"}}"
    )
    text, _, _ = _generate(critic_prompt, provider=provider, model=model, api_key=api_key)
    approved = '"approved": true' in text.lower() or '"approved":true' in text.lower()
    return {"approved": approved, "feedback": text}


def final_answer(
    prompt: str,
    run_result: dict,
    chart_mode: bool = True,
    provider: Optional[str] = None,
    model: Optional[str] = None,
    api_key: Optional[str] = None,
) -> dict[str, Any]:
    logs = run_result.get("logs", "")
    if _use_mock(provider, api_key):
        md = _mock_final_answer(prompt, logs)
        charts = []
        if chart_mode and run_result.get("output_metadata"):
            charts = [{
                "type": "bar",
                "title": "Summary",
                "data": [{"name": "rows", "value": run_result["output_metadata"][0].get("rows", 0)}],
            }]
        return {"final_answer": md, "chart_objects": charts, "provider": "mock", "model": "mock"}
    fa_prompt = (
        f"Write markdown insights for the user question using only execution output.\n"
        f"Question: {prompt}\nOutput:\n{logs}"
    )
    text, prov_id, model_id = _generate(fa_prompt, provider=provider, model=model, api_key=api_key)
    charts: list[dict[str, Any]] = []
    if chart_mode:
        charts = generate_chart_objects(prompt, run_result, provider=provider, model=model, api_key=api_key)
    return {"final_answer": text, "chart_objects": charts, "provider": prov_id, "model": model_id}


def generate_chart_objects(
    prompt: str,
    run_result: dict,
    provider: Optional[str] = None,
    model: Optional[str] = None,
    api_key: Optional[str] = None,
) -> list[dict[str, Any]]:
    logs = str(run_result.get("logs", ""))[:12000]
    previews = run_result.get("previews", {})
    output_metadata = run_result.get("output_metadata", [])
    if _use_mock(provider, api_key):
        if output_metadata:
            first = output_metadata[0]
            return [{"type": "bar", "title": "Output rows", "data": [{"name": "rows", "value": first.get("rows", 0)}]}]
        return []
    if not logs and not previews and not output_metadata:
        return []
    chart_prompt = (
        "Create up to 3 simple chart specs for the analysis output. "
        "Return ONLY JSON array. Each object must have: type ('bar'|'line'|'pie'), "
        "title, data (array of objects), xKey, yKey. Use small grounded data only. "
        "If charts are not appropriate, return [].\n\n"
        f"User question: {prompt}\n"
        f"Execution logs:\n{logs}\n\n"
        f"Output metadata JSON:\n{json.dumps(output_metadata, default=str)[:4000]}\n"
        f"Previews JSON:\n{json.dumps(previews, default=str)[:8000]}"
    )
    text, _, _ = _generate(chart_prompt, provider=provider, model=model, api_key=api_key)
    parsed_text = text.strip()
    if parsed_text.startswith("```"):
        parsed_text = parsed_text.split("```", 2)[1]
        if parsed_text.startswith("json"):
            parsed_text = parsed_text[4:]
        parsed_text = parsed_text.strip()
    try:
        parsed = json.loads(parsed_text)
    except Exception:
        return []
    if not isinstance(parsed, list):
        return []
    return [c for c in parsed if isinstance(c, dict) and isinstance(c.get("data"), list)][:3]


def get_llm_catalog() -> dict:
    return list_providers()
