import os
from typing import Any, Optional

import google.generativeai as genai

from gemini_models import resolve_model

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")


def _use_mock() -> bool:
    return not GEMINI_API_KEY.strip()


def _get_model(model: Optional[str] = None):
    genai.configure(api_key=GEMINI_API_KEY)
    preset = resolve_model(model)
    return genai.GenerativeModel(preset.api_model), preset


def _mock_codegen(prompt: str) -> str:
    return f'''# Generated for: {prompt[:80]}
import pandas as pd
result = df1.describe() if "df1" in dir() else pd.DataFrame({{"note": ["upload a dataset first"]}})
print(result)
'''


def _mock_final_answer(prompt: str, stdout: str) -> str:
    return f"## Quick Analysis\n\n**Question:** {prompt}\n\n**Findings:**\n\n```\n{stdout[:2000]}\n```\n"


def generate_code(
    prompt: str,
    context: str = "",
    critic_feedback: str = "",
    model: Optional[str] = None,
) -> dict[str, Any]:
    full_prompt = prompt
    if context:
        full_prompt = f"{context}\n\nUser request:\n{prompt}"
    if critic_feedback:
        full_prompt += f"\n\nFix based on critic feedback:\n{critic_feedback}"
    if _use_mock():
        code = _mock_codegen(prompt)
        return {"code": code, "explanation": "Mock codegen (set GEMINI_API_KEY for real LLM)", "model": "mock"}
    gmodel, preset = _get_model(model)
    system = (
        "You are a Python data analyst. Return only executable pandas/numpy code. "
        "DataFrames are df1, df2, ... Print labeled results."
    )
    resp = gmodel.generate_content(f"{system}\n\n{full_prompt}")
    code = (resp.text or "").strip()
    if code.startswith("```"):
        code = code.split("```", 2)[1]
        if code.startswith("python"):
            code = code[6:]
        code = code.strip()
    return {"code": code, "explanation": f"Generated by {preset.label}", "model": preset.preset_id}


def critic_evaluate(
    code: str,
    run_result: dict,
    prompt: str,
    model: Optional[str] = None,
) -> dict[str, Any]:
    if _use_mock():
        if run_result.get("status") == "completed":
            return {"approved": True, "feedback": "Mock critic approved"}
        return {"approved": False, "feedback": run_result.get("error", {}).get("message", "Execution failed")}
    gmodel, _ = _get_model(model)
    resp = gmodel.generate_content(
        f"Approve Python analysis code if output answers the question.\n"
        f"Question: {prompt}\nCode:\n{code}\nOutput logs:\n{run_result.get('logs','')}\n"
        f"Reply JSON: {{\"approved\": true/false, \"feedback\": \"...\"}}"
    )
    text = (resp.text or "").strip()
    approved = '"approved": true' in text.lower() or '"approved":true' in text.lower()
    return {"approved": approved, "feedback": text}


def final_answer(
    prompt: str,
    run_result: dict,
    chart_mode: bool = True,
    model: Optional[str] = None,
) -> dict[str, Any]:
    logs = run_result.get("logs", "")
    if _use_mock():
        md = _mock_final_answer(prompt, logs)
        charts = []
        if chart_mode and run_result.get("output_metadata"):
            charts = [{"type": "bar", "title": "Summary", "data": [{"name": "rows", "value": run_result["output_metadata"][0].get("rows", 0)}]}]
        return {"final_answer": md, "chart_objects": charts}
    gmodel, _ = _get_model(model)
    resp = gmodel.generate_content(
        f"Write markdown insights for the user question using only execution output.\n"
        f"Question: {prompt}\nOutput:\n{logs}"
    )
    return {"final_answer": (resp.text or "").strip(), "chart_objects": []}
